services:
  web:
    build: .
    container_name: polyclinic_app
    ports:
      - "8080:8080"
    environment:
      JDBC_URL: "jdbc:postgresql://localhost:5432/polyclinic_db"
      DB_USER: "postgres"
      DB_PASSWORD: "password"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: polyclinic_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s

volumes:
  postgres_data: {}